Create cheatsheet
HarisGusic/tuterm pull request #17
Opened 2022-10-06 17:00 UTC by smsalamon

Resolves #10 

Cheatsheet with tuterm commands and shell functions that can be used with `cheat`.

2022-10-07 16:58 UTC, smsalamon commented
@veracioux Let me know if I've missed anything or you want anything changed. Thanks!

2022-10-07 19:37 UTC, veracioux requested changes
Thanks for your changes. I have left a review requesting some changes.

2022-10-07 19:37 UTC, veracioux commented on docs/cheatsheet
> +option 'option'
Change `'option'` to `<OPTION>` for consistency.

2022-10-08 13:09 UTC, veracioux approved these changes
@smsalamon Thanks. Merging now.

2022-10-08 13:10 UTC, merged